# Exemplo de código Python para ser integrado ao Portfólio

In [10]:
import pandas as pd

df = pd.read_csv('data-fictional.csv')
df['currency'] = [float(x.split('$')[1]) for x in df['currency'].values]
df.head()

,name,phone,address,postalZip,region,country,currency
0,Fletcher Combs,1-584-487-3495,363-2705 Ac Ave,JB4M 8YD,Gloucestershire,United Kingdom,63.84
1,Cynthia Johns,1-616-654-9083,367-618 Sed Avenue,U1 6SD,Kinross-shire,United Kingdom,68.26
2,Ryder Murray,(535) 334-4198,4059 Justo Rd.,34078,Delaware,United States,68.47
3,Shelly Short,1-841-326-2077,"P.O. Box 445, 4731 Vitae Ave",LV4 7XA,Kincardineshire,United Kingdom,32.82
4,James Goff,1-353-252-2755,724-9987 Proin St.,W3 7IC,Midlothian,United Kingdom,45.88

In [11]:
df.describe()

        currency
count  100.00000
mean    52.81800
std     28.47822
min      0.29000
25%     26.52750
50%     55.64000
75%     74.43500
max     99.82000